import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { useUser } from "@clerk/nextjs";
import { SignOutButton } from "@clerk/nextjs";

const Home: NextPage = () => {
  // const { user } = useUser();
  const { isLoaded, isSignedIn, user } = useUser();

  // tRPC lets you make server functions on vercel
  // fetch datas from database
  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {isSignedIn && <div><SignOutButton /></div>}
        <div>
          {data?.map((post) => (<div key={post.id}>{post.content}</div>))}
        </div>
      </main>
    </>
  );
};

export default Home;
